#
# File: https://github.com/data-engineering-helpers/dpp-images/blob/main/.github/workflows/docker.yml
# 
# Dockerfiles:
# * Base: https://github.com/data-engineering-helpers/dpp-images/blob/main/corretto-emr-dbs-universal-base/Dockerfile
# * Python: https://github.com/data-engineering-helpers/dpp-images/tree/main/corretto-emr-dbs-universal-pyspark/Dockerfile
# * Scala: https://github.com/data-engineering-helpers/dpp-images/blob/main/corretto-emr-dbs-universal-spark-scala/Dockerfile
#
# Docker Cloud builds:
# * https://docs.docker.com/build-cloud/
# * https://docs.docker.com/build-cloud/ci/
# * Cloud builders: https://app.docker.com/build/accounts/infrahelpers/builders
#
# For SBOM and attestations of provenance:
# * https://docs.docker.com/scout/policy/#supply-chain-attestations
# * https://docs.docker.com/build/metadata/attestations/
#   * With GitHub Actions:
#     https://docs.docker.com/build/ci/github-actions/attestations/
#
# Scheduling builds:
# * https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
# * https://crontab.guru/#0_0_1_*_*
#
name: Build and publish container images onto Docker Hub

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 0 1 * *" # Trigger a build every 1st day of the month at 00:00 UTC
  workflow_dispatch:

env:
  ORG_NAME: infrahelpers
  IMAGE_NAME: infrahelpers/dpp
    
jobs:
  build_base_images:
    strategy:
      matrix:
        # https://www.java.com/releases/matrix/
        jdk_version: [8, 11, 17]

    environment: docker-hub

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "${{ env.ORG_NAME}}/default"
          install: true

      # https://github.com/docker/metadata-action
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
        
      - name: Run privileged
        run: sudo docker run --privileged --rm tonistiigi/binfmt --install arm64

      # https://github.com/docker/build-push-action
      - name: Build base corretto image
        id: docker_build_corretto_base
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./corretto-emr-dbs-universal-base
          file: ./corretto-emr-dbs-universal-base/Dockerfile
          build-args: |
            JDK_VERSION=${{ matrix.jdk_version }}
          push: true
          provenance: mode=max
          sbom: true
          tags: |
            ${{ env.IMAGE_NAME }}:jdk${{ matrix.jdk_version }}
            ${{ env.IMAGE_NAME }}:latest
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:build-cache-jdk
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:build-cache-jdk,mode=max
          platforms: linux/amd64,linux/arm64/v8

  build_scala_images:
    needs: build_base_images
    strategy:
      matrix:
        sbt_version: [1.10.2]

    environment: docker-hub

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "${{ env.ORG_NAME}}/default"
          install: true

      # https://github.com/benjlevesque/short-sha
      - name: Load short SHA1
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      # https://github.com/docker/build-push-action
      - name: Build corretto with sbt installed
        id: docker_build_corretto_sbt
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./corretto-emr-dbs-universal-spark-scala
          file: ./corretto-emr-dbs-universal-spark-scala/Dockerfile
          # As of end 2024, only Java 8 is supported for Spark
          build-args: |
            JDK_VERSION=8
            SBT_VERSION=${{ matrix.sbt_version }}
          push: true
          provenance: mode=max
          sbom: true
          tags: |
            ${{ env.IMAGE_NAME }}:jdk8-sbt${{ matrix.sbt_version }}
            ${{ env.IMAGE_NAME }}:jdk8-sbt${{ matrix.sbt_version }}-${{ env.SHA }}
            ${{ env.IMAGE_NAME }}:jdk8-sbt
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:build-cache-jdk8-sbt
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:build-cache-jdk8-sbt,mode=max
          platforms: linux/amd64,linux/arm64/v8

  build_python_images:
    needs: build_base_images
    strategy:
      matrix:
        # https://www.java.com/releases/matrix/
        jdk_version: [8, 11, 17]
        # Use the latest releases for each minor version:
        # https://www.python.org/downloads/source/
        python_micro_version: [3.8.20, 3.9.20, 3.10.15, 3.11.10, 3.12.7]

    environment: docker-hub

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "${{ env.ORG_NAME}}/default"
          install: true

      - name: Extract Minor Version
        id: extract_minor_version
        run: |
          minor_version=$(echo "${{ matrix.python_micro_version }}" | cut -d. -f1-2)
          echo "minor_version=${minor_version}" >> $GITHUB_OUTPUT

      # https://github.com/benjlevesque/short-sha
      - name: Load short sha
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      # https://github.com/docker/build-push-action
      - name: Build Corretto with EMR-/Databricks-compatible Python installed
        id: docker_build_corretto_python
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./corretto-emr-dbs-universal-pyspark
          file: ./corretto-emr-dbs-universal-pyspark/Dockerfile
          build-args: |
            JDK_VERSION=${{ matrix.jdk_version }}
            PYTHON_MINOR_VERSION=${{ steps.extract_minor_version.outputs.minor_version }}
            PYTHON_MICRO_VERSION=${{ matrix.python_micro_version }}
          push: true
          provenance: mode=max
          sbom: true
          tags: |
            ${{ env.IMAGE_NAME }}:jdk${{ matrix.jdk_version }}-python${{ steps.extract_minor_version.outputs.minor_version }}
            ${{ env.IMAGE_NAME }}:jdk${{ matrix.jdk_version }}-python${{ steps.extract_minor_version.outputs.minor_version }}-${{ env.SHA }}
            ${{ env.IMAGE_NAME }}:jdk${{ matrix.jdk_version }}-python${{ matrix.python_micro_version }}
            ${{ env.IMAGE_NAME }}:jdk${{ matrix.jdk_version }}-python${{ matrix.python_micro_version }}-${{ env.SHA }}
            ${{ env.IMAGE_NAME }}:jdk${{ matrix.jdk_version }}-python
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:build-cache-jdk-python
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:build-cache-jdk-python-sbt,mode=max
          platforms: linux/amd64,linux/arm64/v8

