name: Push Docker images on Docker Hub

on:
  workflow_dispatch:

jobs:
  build_base_images:
    strategy:
      matrix:
        jdk_version: [8, 11]
    environment: docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Run privileged
        run: sudo docker run --privileged --rm tonistiigi/binfmt --install arm64

      - name: Build base corretto image
        id: docker_build_corretto_base
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./corretto-emr-dbs-universal-base
          file: ./corretto-emr-dbs-universal-base/Dockerfile
          build-args: |
            JDK_VERSION=${{ matrix.jdk_version }}
          push: true
          tags: infrahelpers/dpp:jdk${{ matrix.jdk_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_scala_images:
    needs: build_base_images
    strategy:
      matrix:
        sbt_version: [1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.9.1, 1.9.2]
    environment: docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build corretto with sbt installed
        id: docker_build_corretto_sbt
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./corretto-emr-dbs-universal-spark-scala
          file: ./corretto-emr-dbs-universal-spark-scala/Dockerfile
          # Only Java 8 is supported for Spark
          build-args: |
            JDK_VERSION=8
            SBT_VERSION=${{ matrix.sbt_version }}
          push: true
          tags: infrahelpers/dpp:jdk8-sbt${{ matrix.sbt_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max